//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_8_MVC_Batool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Major
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Major()
        {
            this.AspNetUsers = new HashSet<AspNetUser>();
            this.Courses = new HashSet<Cours>();
        }
    
        public int MajorID { get; set; }
        public string MajorName { get; set; }
        public string MajorImage { get; set; }
        public string Major_Description { get; set; }
        public Nullable<int> Price_OfHour { get; set; }
        public Nullable<int> Number_OfHour { get; set; }
        public Nullable<int> Faculity_ID { get; set; }
        public Nullable<double> minimum_rate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cours> Courses { get; set; }
        public virtual Faculty Faculty { get; set; }
    }
}
